// src/utils/consts.js
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REG_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const SHOPS_ROUTE = '/admin/shops'
export const EMPLOYEES_ROUTE = '/admin/employees'
export const SUPPLIES_ROUTE = '/admin/supplies'
export const CREATE_SUPPLIES_ROUTE = '/admin/create-supply'
export const ADMIN_PROD = '/admin/products'
export const EMPLOYEE_PROD = '/employee/products'
export const BOUQUETS_ROUTE = '/employee/bouquets'
export const CREATE_BOUQUET_ROUTE = '/employee/create-bouquet'